name: continous-integration
on:
  pull_request: main
jobs:
  unit-test-on-pull-request:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v6
      - name: setup-python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.14' 
      - name: setup-pip-modules
        run: python -m pip install -r requirements.txt
      - run: pytest
